# Generated by Django 2.1.7 on 2019-05-02 23:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0002_auto_20190502_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 2, 23, 26, 51, 231036, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 2, 23, 26, 51, 231036, tzinfo=utc)),
        ),
    ]
