# Generated by Django 2.1.7 on 2019-05-03 14:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0003_auto_20190502_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 3, 14, 26, 27, 98359, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 3, 14, 26, 27, 98359, tzinfo=utc)),
        ),
    ]
